terraform:
  roles:
    hub: "arn:aws:iam::635729853710:role/STLA-Terraform-LZ-Provisioning"
    deploy: "arn:aws:iam::265347365596:role/STLA-Terraform-LZ-Provisioning"
    shared:
      prod: "arn:aws:iam::676808587751:role/STLA-Terraform-LZ-Provisioning"
      nonprod: "arn:aws:iam::972039324284:role/STLA-Terraform-LZ-Provisioning"

alt_regions:
  us-east-1: "us-east-1"
