terraform:
  roles:
    hub: "arn:aws:iam::787987996086:role/STLA-Terraform-LZ-Provisioning"
    deploy: "arn:aws:iam::893893329401:role/STLA-Terraform-LZ-Provisioning"
    shared:
      prod: "arn:aws:iam::453219028467:role/STLA-Terraform-LZ-Provisioning"
      nonprod: "arn:aws:iam::783023575330:role/STLA-Terraform-LZ-Provisioning"

alt_regions:
  eu-west-3: "eu-west-1"
  eu-west-1: "eu-west-3"
