terraform:
  roles:
    hub: "arn:aws:iam::720948693958:role/STLA-Terraform-LZ-Provisioning"
    deploy: "arn:aws:iam::899011411636:role/STLA-Terraform-LZ-Provisioning"
    shared:
      prod: "arn:aws:iam::893749570280:role/STLA-Terraform-LZ-Provisioning"
      nonprod: "arn:aws:iam::191080303679:role/STLA-Terraform-LZ-Provisioning"

alt_regions:
  eu-west-3: "eu-west-1"
  eu-west-1: "eu-west-3"
